  server:
    port: 80

  spring:
    application:
      name: cloud-order-service

  eureka:
    client: #将客户端注册到 eureka 服务列表内
      # 表示是否将自己注册进 EurekaServer 默认为 true
      register-with-eureka: true
      # 是否从 EurekaServer 抓取已有的注册信息，默认为 true。 单节点无所谓，集群必须设置为 true 才能配合 Ribbon 使用
      fetchRegistry: true
      service-url:
        #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
      instance-id: order80