server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:  #网关路由配置
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能, 利用微服务名称进行路由
      routes:
        - id: payment_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          #  uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/payment/get/**            #断言，路径匹配 注意：Path 中 P 为大写
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 1024
            - PrefixPath=/payment #在请求路径前面加上 /payment

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    instance-id: cloud-gateway-9527
    hostname: cloud-gateway-9527
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/